#TUDO QUE ESTÁ ENTRE PARÊNTESE () E ASPAS "" É UMA MENSAGEM, MAS PARA FAZER ESSA MENSAGEM SER EXIBIDA NA TELA VOCÊ DEVE UTILIZAR O FUNÇÃO PRINT
print("Olá, mundo!")

#SE NÚMEROS FOREM ESCRITOS SEM ASPAS OQUE SERÁ EXIBIDO NA TELA VAI SER O RESULTADO DO CALCULO ENTRE ELES
print(7+2)

#SE APENAS COLOCAR ASPAS NOS NÚMEROS, PRESERVANDO OS SINAIS, ELES IRAM SE UNIR
print('7'+'2')

#VARIÁVEL: UMA VARIÁVEL É COMO SE FOSSE UM OBJETO NO PYTHON. VARIÁVEIS SERVEM PARA ARMAZENAREM VALORES, VOCÊ ESCOLHE UM NOME PRA VARIÁVEL MAS ELAS SEMPRE PRECISAM ESTAR ACOMPANHADA DE UM SINAL DE IGUAL = E O SEU VALOR, PARA QUE O PYTHON CONSIGA ENTENDER QUE AQUILO É UMA VARIÁVEL E QUE ELA ESTÁ RECEBENDO TAL VALOR
#EXEMPLO:
Nome= "Arthur"
Idade=17
Peso=59.60

#EM ALGUNS CASOS O SINAL DE + SERVE PARA UNIR NÚMEROS, PORÉM ISTO NÃO FUNCIONA COM MENSAGENS. NESTES CASOS DEVEREMOS UTILIZAR A VIRGULA ,
#EXEMPLO:
print(Nome, Idade, Peso)

#SE EU QUISER FAZER UM PROGRAMA QUE INTERAJA COM A PESSOA QUE ESTÁ NELE, DEVO ADICIONAR O COMANDO INPUT NELE.
#EXEMPLO:
Nomes=input("Qual seu nome?")
Idades=input("Qual é sua idade?")
Pesos=input("Qual é seu peso?")
#O RESPOSTA QUE A PESSOA DIGITAR SERÁ O VALOR DA VARIÁVEL.
print(Nomes, Idades, Pesos)